### ISSUE TITLE
Overflow Issue

### ISSUE THREAD

**Issue by coocoozz** [jpillora/backoff#11]
When we use the library, if we don't call Reset() forever, numeric overflow is generated

In ForAttempt(), "durf" variable is float64.
```
durf := minf * math.Pow(factor, attempt)
```

but, "dur" variable is int64
```
dur := time.Duration(durf)
```

so, if the range of "durf" over the range of "dur", "dur" variable is overflowed.

**Comment by jpillora** [comment]
Thanks will look into this soon

**Comment by timjchin** [comment]
Ran into this issue - thank you for fixing it! While debugging it, noticed the statement:
`durf := minf * math.Pow(factor, attempt)`

I'm curious why this is `minf` multiplied by `2^x` instead of `minf + 2^x`? This causes the exponential backoff to increase at a faster rate:
![image](https://cloud.githubusercontent.com/assets/1714798/23860941/e0be8228-07de-11e7-8741-646ba4218201.png)

[Google's docs](https://cloud.google.com/storage/docs/exponential-backoff) suggest using:
`duration = min(((2^n)+random_number_milliseconds), maximum_backoff)`

Given a 60s max:
`durf := minf * math.Pow(factor, attempt)` reaches a 60s timeout after 10 attempts:
```
0: 100ms
1: 200ms
2: 400ms
3: 800ms
4: 1.6s
5: 3.2s
6: 6.4s
7: 12.8s
8: 25.6s
9: 51.2s
10: 1m0s
```
while:
`durf := minf + math.Pow(factor, attempt)` takes 36 attempts:
```
0: 100.000001ms
1: 100.000002ms
2: 100.000004ms
3: 100.000008ms
4: 100.000016ms
5: 100.000032ms
6: 100.000064ms
7: 100.000128ms
8: 100.000256ms
9: 100.000512ms
10: 100.001024ms
11: 100.002048ms
12: 100.004096ms
13: 100.008192ms
14: 100.016384ms
15: 100.032768ms
16: 100.065536ms
17: 100.131072ms
18: 100.262144ms
19: 100.524288ms
20: 101.048576ms
21: 102.097152ms
22: 104.194304ms
23: 108.388608ms
24: 116.777216ms
25: 133.554432ms
26: 167.108864ms
27: 234.217728ms
28: 368.435456ms
29: 636.870912ms
30: 1.173741824s
31: 2.247483648s
32: 4.394967296s
33: 8.689934592s
34: 17.279869184s
35: 34.459738368s
36: 1m0s
```

Is the goal a more aggressive timeout?
